build-job:
  stage: build
  script:
    - grep -rn '[[:blank:]]$' *.v && exit 1
    - grep -rn '.\{81\}' *.v && exit 1
    - coq_makefile -f _CoqProject -o Makefile
    - make clean
    - make
    - q=`coqchk -silent -o -Q . ZFC *.vo 2>&1`; echo "$q" && r=`echo "$q" | grep -P '(ZFC\.|Coq\.)' | sort | cut -f 3 -d . | paste -sd \ ` && [[ "$r" == "FunctionalExtensionality IndefiniteDescription PropExtensionality Extensionality IN Infinity Powerset Regularity Replacement Union set" ]] || exit 1
