build-job:
  stage: build
  script:
    - coq_makefile -f _CoqProject -o Makefile
    - make clean
    - make
    - grep -rn '[[:blank:]]$' ~/TeX/waterloo/zfc-coq/*.v && exit 1
    - grep -rn '.\{81\}'  ~/TeX/waterloo/zfc-coq/*.v && exit 1
    - coqchk -silent -o -Q . ZFC *.vo
