build-job:
  stage: build
  script:
    - make clean
    - make

syntax-check:
  stage: test
  script:
    - /home/djao/bin/check-coq.sh

axiom-check:
  stage: test
  script:
    - coqchk -silent -o -Q . ZFC *.vo
